version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 3
  - labels:
      - dependencies
      - npm
  reviewers:
    - theotime2005
  assignees:
    - theotime2005
  commit-message:
    prefix: bump
    prefix-development: bump
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 2
  labels:
    - dependencies
    - workflow
  reviewers:
    - theotime2005
  assignees:
    - theotime2005
  commit-message:
    prefix: bump
    prefix-development: bump
    include: scope
