name: Enable Auto Merge

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  enable_auto_merge:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ','), 'Ready to merge') && github.event.pull_request.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Auto Merge
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const pull_number = context.payload.pull_request.number;

            // Récupérer l'ID du pull request (node_id)
            const { repository } = await github.graphql(`
              query($owner: String!, $repo: String!, $pull_number: Int!) {
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $pull_number) {
                    id
                  }
                }
              }
            `, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number
            });

            await github.graphql(`
              mutation($pullRequestId: ID!) {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: $pullRequestId,
                  mergeMethod: MERGE
                }) {
                  pullRequest {
                    id
                  }
                }
              }
            `, {
              pullRequestId: repository.pullRequest.id
            });
