name: Update Version on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  update-version:
    if: ${{ github.event.pull_request.merged == true }} # Check if the PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Switch to the main branch
        run: git checkout main

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 'latest'

      - name: Determine version bump
        id: version_bump
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"[BUGFIX]"* ]]; then
            echo "news=patch" >> $GITHUB_ENV
            npm version patch
          elif [[ "${{ github.event.pull_request.title }}" == *"[MINORFEATURE]"* ]]; then
            echo "news=minor" >> $GITHUB_ENV
            npm version minor
          elif [[ "${{ github.event.pull_request.title }}" == *"[MAJORFEATURE]"* ]]; then
            echo "news=major" >> $GITHUB_ENV
            npm version major
          else
            echo "news=none" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.news != 'none'
        run: |
          git commit -am "Bump version"
          git push
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
