name: Update packages.yml
on:
  push:
    branches:
      - test-action

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout
      - name: Setup node js
        uses: actions/setup-node
        with:
          node-version: 'latest'
      - name: Install packages
        run: npm install
      - name: Update dependencies
        run: npm update
      - name: Commit and push changes
        run: |
          git add package.json package-lock.json
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update packages"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
