name: Update packages.yml

on:
  push:
    branches:
      - main
    schedule:
        - cron: '0 8 * * MON'

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
      - name: Setup node js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'latest'
      - name: Install packages
        run: npm install
      - name: Update dependencies
        run: npm update
      - name: Commit and push changes
        run: |
          git add package.json package-lock.json
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          commit_date=date
          git commit -m "Update packages $commit_date"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
