name: Update Version on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
    contents: write

jobs:
  update-version:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Switch to the main branch
        run: git checkout main

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 'latest'

      - name: Determine version bump
        id: version_bump
        run: |
          if [ "${{ github.event.pull_request.title }}" == "[BUGFIX]"* ]; then
            echo "bump_type=minor" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.title }}" == "[FEATURE]"* ]; then
            echo "bump_type=major" >> $GITHUB_ENV
          else
            echo "bump_type=none" >> $GITHUB_ENV
          fi

      - name: Bump version
        if: env.bump_type != 'none'
        run: npm version ${{ env.bump_type }}

      - name: Commit and push changes
        if: env.bump_type != 'none'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
